blank_issues_enabled: false
contact_links:
  - name: Nuxt Community Discord
    url: https://discord.nuxtjs.org/
    about: Consider asking questions about the module here.
  - name: nuxt-vite documentation
    url: https://github.com/richardeschloss/nuxt-vite
    about: Check our documentation before reporting issues or questions.
